language: generic

dist: bionic

before_install:
- mkdir $HOME/.fonts
- cp -a $TRAVIS_BUILD_DIR/fonts/. $HOME/.fonts/
- fc-cache -f -v

install:
- source ./texlive/texlive_install.sh

cache:
  directories:
  - "/tmp/texlive"
  - "$HOME/.texlive"

  before_script: cd $TRAVIS_BUILD_DIR/

script:
- texliveonfly cv.tex --compiler=lualatex
- texliveonfly resume.tex --compiler=lualatex
- texliveonfly coverletter.tex --compiler=lualatex
- latexmk -pdflua -output-directory="outputs/" cv.tex
- latexmk -pdflua -output-directory="outputs/" resume.tex
- latexmk -pdflua -output-directory="outputs/" coverletter.tex

deploy:
  provider: releases
  api_key:
    secure: s3P13aqVUeQW0PVQVDgY8otBrZ36IXbzYVSRqoZNtF9l35HjOSaXp9+Pa8AEPjaArqiRXO/M9+D/iQTrTvfPJSrMo6O/l5C2x0honCLgWiIMe57Y2tRHFEQLnSAhrQ+VbvEI79atj8m6JNRy2vc80L6ortpUXTBHRKRDysL/9kZkQ0x04MZUCoPtluQrIGbfjrMpUmZNmrxbDRCrTCRRlhRYCVvoXnLDlU+mBfLhBRY+XbS3700tCdZfftLHJSuznE0CqZC9xbAF1c/vViMHeldIB5IVXLE1vpu1yFvEu1Gpo+Ip8bF8maDTopYNRxV9mCX7UaW0qMLCCP6kJ6BjiG5d2NXNWNOtG4hxO2+g1t5UeZLwq1O8eduzamiMgJS7vybirVE8HPrlWxMBzbFlFkub+I9CBhTue/ra7z1Pal0LRXXNWUNopVz+/H6wIUDC59GHqptYFS04BAeZmjZlZV70Acs2dsMmelV7SsYZHtuGQolrwosjWXk16oqhLuyXDkQfxVUz0Zh0uZAE1VfQaXdcJdgH4migdb1q7A3vGDRPuFO1dQv89DpTgtzwaI3ihaNcmIlfmGl1qXraacRLGnSReOybzpWDvSkxks0SdfeF+dPtBv0au1LUWiwEUD922Tb8vCZ+jCdeXsTSwpVkn8FhABcBXcYR247skM+OViI=
  file:
    - ./outputs/cv.pdf
    - ./outputs/resume.pdf
    - ./outputs/coverletter.pdf
  on:
    repo: zulkiflizaki/personal-cv-resume
  skip_cleanup: 'true'
